---
# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'upload-artifact-verify'
description: "GitHub Action to upload an artifact and verify it is downloadable."
author: 'cytopia'
branding:
  icon: 'code'
  color: 'red'

inputs:
  name:
    description: 'The filename of the uploaded file'
    required: true
  path:
    description: 'The local file to upload'
    required: true

runs:
  using: "composite"
  steps:

    # ------------------------------------------------------------
    # Upload Artifact (try 1)
    # ------------------------------------------------------------

    - name: "[try 1] Upload artifact"
      id: upload-1
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: "[try 1] Create temporary directory"
      id: tmp-dir-1
      shell: bash
      run: echo "::set-output name=path::$( mktemp -d )"
      if: ${{ steps.upload-1.outcome == 'success' }}

    - name: "[try 1] Download artifact"
      id: download-1
      continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ steps.tmp-dir-1.outputs.path }}
      if: ${{ steps.upload-1.outcome == 'success' }}


    # ------------------------------------------------------------
    # Upload Artifact (try 2)
    # ------------------------------------------------------------

    - name: "[try 2] Upload artifact"
      id: upload-2
      continue-on-error: true
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
      if: ${{ steps.upload-1.outcome == 'failure' || steps.download-1.outcome == 'failure' }}

    - name: "[try 2] Create temporary directory"
      id: tmp-dir-2
      shell: bash
      run: echo "::set-output name=path::$( mktemp -d )"
      if: ${{ steps.upload-2.outcome == 'success' }}

    - name: "[try 2] Download artifact"
      id: download-2
      continue-on-error: true
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ steps.tmp-dir-2.outputs.path }}
      if: ${{ steps.upload-2.outcome == 'success' }}


    # ------------------------------------------------------------
    # Upload Artifact (final try)
    # ------------------------------------------------------------

    - name: "[final] Upload artifact"
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}

    - name: "[final] Create temporary directory"
      id: tmp-dir-x
      shell: bash
      run: echo "::set-output name=path::$( mktemp -d )"

    - name: "[final] Download artifact"
      uses: actions/download-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ steps.tmp-dir-x.outputs.path }}
